services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:5000"
  mongo:
    image: "mongo:6.0.13-jammy"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
